name: CI
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit:run

      - name: Run integration tests
        run: npm run test:integration:run

  lint-commitmsg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate pull request commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from "${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}" --to "${{ github.event.pull_request.head.sha }}" --verbose
